# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, cassava, filepath, text, vector }:

cabal.mkDerivation (self: {
  pname = "data-preparation";
  version = "0.1";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [ cassava filepath text vector ];
  meta = {
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
